vim.opt.scrolloff = 12
vim.opt.signcolumn = "no" 
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.expandtab = true
vim.opt.relativenumber = true
vim.opt.nu = true
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.autochdir = true
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.background = "dark" -- or "light" for light mode
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.writebackup = false

vim.g.python_highlight_space_errors = false
