FROM ubuntu:latest

# pandoc in ubuntu is old, and does not support formulas in GFM
RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pandoc texlive-full 

RUN mkdir /data

WORKDIR /data

ENTRYPOINT ["pandoc"]
