[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
